engines:
  duplication:
    exclude_paths:
    - "src/dem-afterlife-ui/**/*.test.js"
    - "src/dem-afterlife-ui/src/app/api/__fakeApi__/**"
    - "src/dem-afterlife-ui/src/app/api/__fakeData__/**"
    - "src/dem-afterlife-ui/node_modules/**"
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70
          filters:
          - "(ImportDeclaration _ (ImportDefaultSpecifier _ (Identifier _)) _ (StringLiteral _))"
          - "(JSXOpeningElement (attributes (JSXAttribute name (JSXIdentifier className) value (JSXExpressionContainer expression (Identifier _))) (JSXAttribute name (JSXIdentifier onClick) value (JSXExpressionContainer expression (Identifier _))) (JSXAttribute name (JSXIdentifier role) value (JSXExpressionContainer expression (StringLiteral _))) (JSXAttribute name (JSXIdentifier tabIndex) value (JSXExpressionContainer expression (NumericLiteral)))) name (JSXIdentifier _))"
          patterns:
          - "**/*.js"
          - "**/*.jsx"
  git-legal:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO