engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  git-legal:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO