engines:
  git-legal:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO