engines:
  eslint:
    enabled: true
    config:
      config: src/dem-afterlife-ui/.eslintrc
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
ratings:
  paths:
  - src/dem-afterlife-ui/**/*.js
  - src/dem-afterlife-ui/**/*.jsx
exclude_paths:
- src/dem-afterlife-ui/node_modules/**
- src/dem-afterlife-ui/**/*.test.js
- src/dem-afterlife-ui/src/app/api/__fakeApi__/**
- src/dem-afterlife-ui/src/app/api/__fakeData__/**