engines:
  duplication:
    exclude_paths:
    - "src/dem-afterlife-ui/**/*.test.js"
    - "src/dem-afterlife-ui/src/app/api/__fakeApi__/**"
    - "src/dem-afterlife-ui/src/app/api/__fakeData__/**"
    - "src/dem-afterlife-ui/node_modules/**"
    enabled: true
    config:
      languages:
        javascript:
          filters:
          - "(ImportDeclaration _ (ImportDefaultSpecifier _ (Identifier _)) _ (StringLiteral _))"
          patterns:
          - "**/*.js"
          - "**/*.jsx"
  git-legal:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO