env:
  global:
    - CC_TEST_REPORTER_ID=53db050b1f96c52dc1bd7442e4f341841a24f425633d0bde6deea882941fc1f8
language: node_js
node_js:
  - "6"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cd src/dem-afterlife-ui
  - yarn
script:
  - yarn test-runInBand
  - yarn buildOnly
before_install:
- export TZ=Europe/Kiev
after_script:
  - cd ../../
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT