import React from 'react';
import PropTypes from 'prop-types';

const Presentation = ({children}) =>
    <div>
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {'Some fake dataSome fake data'}
        {children}
    </div>;
Presentation.propTypes = {
    children: PropTypes.node
};

export default Presentation;