/* eslint no-undefined:0 */

const userArray = [
  {
    id: 1,
    name: "Buba",
    registrationDate: new Date("2015/01/02 10:10:10"),
    birthday: new Date("2015/01/02 10:10:10"),
    email: "Buba@lol.ua",
    emailConfirmed: true,
    gender: 1,
    rank: "Скаут",
    avatar:
      "http://i70.fastpic.ru/big/2015/0628/36/ccbb1e2cb8ba8dbd379a6a12dc6b8336.jpg",
    signature:
      "[img]http://forums.euw.leagueoflegends.com/board/attachment.php?attachmentid=186257[/img]",
    from: undefined,
    steam: undefined,
    skype: undefined,
    icq: undefined,
    vk: undefined,
    fb: undefined,
    website: undefined,
    profession: undefined,
    interests: undefined,
    groupColor: "#00AA00"
  },
  {
    id: 2,
    name: "Bykawka",
    registrationDate: new Date("2015/01/02 10:10:10"),
    birthday: new Date("2015/01/02 10:10:10"),
    email: "Bykawka@lol.ua",
    emailConfirmed: true,
    gender: 1,
    rank: "Молоковоз",
    avatar: undefined,
    signature: undefined,
    from: undefined,
    steam: undefined,
    skype: undefined,
    icq: undefined,
    vk: undefined,
    fb: undefined,
    website: undefined,
    profession: undefined,
    interests: undefined,
    groupColor: "#fbeab2"
  },
  {
    id: 3,
    name: "Agent005",
    registrationDate: new Date("2015/01/03 10:10:10"),
    birthday: new Date("2015/01/02 10:10:10"),
    email: "Agent005@lol.ua",
    emailConfirmed: false,
    gender: 1,
    rank: "Пешеход",
    avatar: "https://pp.vk.me/c9558/u61600334/a_153d373f.jpg",
    signature: "Бла-бла-бла",
    from: undefined,
    steam: undefined,
    skype: undefined,
    icq: undefined,
    vk: undefined,
    fb: undefined,
    website: undefined,
    profession: undefined,
    interests: undefined,
    groupColor: "#ff00ff"
  },
  {
    id: 4,
    name: "ololoid",
    registrationDate: new Date("2015/01/04 10:10:10"),
    birthday: new Date("2015/01/02 10:10:10"),
    email: "ololoid@lol.ua",
    emailConfirmed: true,
    gender: 1,
    rank: "Боец",
    avatar:
      "http://i72.fastpic.ru/big/2015/0522/10/f93fff451e934900bfb1463615b5b310.png",
    signature: undefined,
    from: undefined,
    steam: undefined,
    skype: undefined,
    icq: undefined,
    vk: undefined,
    fb: undefined,
    website: undefined,
    profession: undefined,
    interests: undefined,
    groupColor: "#99ccff"
  },
  {
    id: 5,
    name: "kto",
    registrationDate: new Date("2015/01/04 10:10:10"),
    birthday: new Date("2015/01/02 10:10:10"),
    email: "4252744@ukr.net",
    emailConfirmed: true,
    gender: 1,
    rank: "Официально сумасшедший",
    avatar:
      "http://i69.fastpic.ru/big/2015/0729/7e/6a397a33426917b4087e403270383c7e.gif",
    signature:
      "__________!///_ _____\r\n_________( @@ )_____\r\n_______ooO-(_)-o o____\r\nПришёл, увидел, забанил. Ещё вопросы?",
    from: undefined,
    steam: undefined,
    skype: undefined,
    icq: undefined,
    vk: undefined,
    fb: undefined,
    website: undefined,
    profession: undefined,
    interests: undefined,
    groupColor: "#ffa510"
  }
];

export default userArray;
